[package]
name = "mitsuami"
description = "Native, declarative, cross-platform UI for Rust"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
mitsuami-core.workspace = true
mitsuami-reactive.workspace = true
mitsuami-widgets.workspace = true

[dev-dependencies]
mitsuami-test.workspace = true

[[test]]
name = "counter"
harness = false

[[test]]
name = "layout"
harness = false

[[test]]
name = "forms"
harness = false

[[test]]
name = "control_flow"
harness = false

[lints]
workspace = true
