[package]
name = "mitsuami-winui"
description = "WinUI 3 (Windows) backend for mitsuami"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
mitsuami-core.workspace = true

[lints]
workspace = true
