//! WinUI 3 (Windows) backend for mitsuami.
//!
//! - Driven imperatively through our own `windows-bindgen` bindings
//!   (`src/bindings.rs`, regenerated by the tool in `bindgen/`). No
//!   `windows-reactor` at runtime.
//! - Containers are `Canvas`es that do no layout of their own; the core
//!   positions every child with `Canvas.Left/Top` and `Width/Height`.
//! - Leaf widgets are stock WinUI controls, measured with `Measure` in the
//!   live tree, with the frame size we imposed lifted for the call.
//! - Escape hatches: [`NativeRender`] for custom widgets, [`NativeView`] for
//!   any XAML element, and XAML shapes for drawn custom widgets.
//! - [`run`] owns the message loop: XAML runs without `Application::Start`,
//!   and the loop ticks the UI before it sleeps.
//!
//! Needs the Windows App Runtime 2.4 or later installed, and the MSVC
//! toolchain (`x86_64-pc-windows-msvc` or `aarch64-pc-windows-msvc`).

#[cfg(all(windows, not(target_env = "msvc")))]
compile_error!(concat!(
    "mitsuami on Windows needs the MSVC toolchain (x86_64-pc-windows-msvc). ",
    "Make it the default once with `rustup set default-host x86_64-pc-windows-msvc`, ",
    "or build with `cargo +1.96-x86_64-pc-windows-msvc ...`."
));

#[cfg(all(windows, target_env = "msvc"))]
mod app;
#[cfg(all(windows, target_env = "msvc"))]
mod backend;
/// The generated WinUI bindings (see `bindgen/filter.txt`): the escape
/// hatch for reaching the native widgets, like `objc2` types on AppKit. They
/// cover what this crate uses, not all of WinUI.
#[cfg(all(windows, target_env = "msvc"))]
#[allow(
    dead_code,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    unused_qualifications,
    clippy::all,
    missing_debug_implementations,
    missing_docs
)]
pub mod bindings;
#[cfg(all(windows, target_env = "msvc"))]
mod capture;
#[cfg(all(windows, target_env = "msvc"))]
mod custom;
#[cfg(all(windows, target_env = "msvc"))]
mod later;
#[cfg(all(windows, target_env = "msvc"))]
mod runtime;
#[cfg(all(windows, target_env = "msvc"))]
mod services;

#[cfg(all(windows, target_env = "msvc"))]
pub use app::{init_for_tests, pump, run};
#[cfg(all(windows, target_env = "msvc"))]
pub use backend::{BackendOptions, WinUiBackend, WinUiHandle};
#[cfg(all(windows, target_env = "msvc"))]
pub use custom::{Emitter, NativeRender, NativeView, WinUiCx, ad_hoc, native};
#[cfg(all(windows, target_env = "msvc"))]
pub use services::WinUiServices;

// What native renders and native views are written with, at the version
// the backend uses: `cast`, `Result`, event revokers.
#[cfg(all(windows, target_env = "msvc"))]
pub use windows_core;
