[package]
name = "mitsuami-appkit"
description = "AppKit (macOS) backend for mitsuami"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
mitsuami-core.workspace = true

[lints]
workspace = true
