[package]
name = "mitsuami-appkit"
description = "AppKit (macOS) backend for mitsuami"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
mitsuami-core.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-foundation.workspace = true
objc2-app-kit.workspace = true
objc2-core-foundation.workspace = true
block2.workspace = true

[lints]
workspace = true
